<?php
if (!defined('ABSPATH')) exit;

class MBTI_Data {

    public static function getQuestions(): array {
        $questions = [
            ['id'=>'q1', 'axis'=>'EI','dir'=> 1,'text'=>'After a party full of people, you feel more energized than drained.'],
            ['id'=>'q2', 'axis'=>'EI','dir'=>-1,'text'=>'You would choose a quiet night at home over an event with many unfamiliar faces.'],
            ['id'=>'q3', 'axis'=>'EI','dir'=> 1,'text'=>'Standing in a group of strangers, you are the one who strikes up a conversation first.'],
            ['id'=>'q4', 'axis'=>'EI','dir'=>-1,'text'=>'After a few hours of nonstop socializing, you feel a strong need to withdraw and recharge alone.'],
            ['id'=>'q5', 'axis'=>'EI','dir'=> 1,'text'=>'Being the center of attention in a group conversation feels fairly natural to you.'],
            ['id'=>'q6', 'axis'=>'EI','dir'=>-1,'text'=>'You only feel truly comfortable sharing personal thoughts with a few close friends.'],
            ['id'=>'q7', 'axis'=>'EI','dir'=> 1,'text'=>'You say yes to a social invitation even when your personal schedule is already quite full.'],
            ['id'=>'q8', 'axis'=>'EI','dir'=>-1,'text'=>'In a meeting, you tend to hear everyone out before offering your own opinion.'],
            ['id'=>'q9', 'axis'=>'EI','dir'=> 1,'text'=>'Your energy rises when working in an open space with people passing by.'],
            ['id'=>'q10','axis'=>'EI','dir'=>-1,'text'=>'You prefer working in a private room or a tucked-away corner over sitting in a busy open office.'],
            ['id'=>'q11','axis'=>'EI','dir'=> 1,'text'=>'When facing a tough problem, your first impulse is to call someone and talk it through.'],
            ['id'=>'q12','axis'=>'EI','dir'=>-1,'text'=>'Before asking for anyone else\'s input, you prefer to think things through on your own first.'],

            ['id'=>'q13','axis'=>'SN','dir'=> 1,'text'=>'When someone pitches a new idea, your first question is usually about the data or how it works in practice.'],
            ['id'=>'q14','axis'=>'SN','dir'=>-1,'text'=>'You find it more exciting to discuss a vision for five years from now than to list what needs to be done tomorrow.'],
            ['id'=>'q15','axis'=>'SN','dir'=> 1,'text'=>'At work, you trust a proven process more than an untested new approach.'],
            ['id'=>'q16','axis'=>'SN','dir'=>-1,'text'=>'An intriguing idea can keep you awake at night, even if no evidence confirms it yet.'],
            ['id'=>'q17','axis'=>'SN','dir'=> 1,'text'=>'You prefer a guide with clear step-by-step instructions over a vague suggestion.'],
            ['id'=>'q18','axis'=>'SN','dir'=>-1,'text'=>'When reading an article, you often wonder about the subtext rather than just taking the information at face value.'],
            ['id'=>'q19','axis'=>'SN','dir'=> 1,'text'=>'You value a colleague who brings concrete data more than one who tells an inspiring story.'],
            ['id'=>'q20','axis'=>'SN','dir'=>-1,'text'=>'You easily connect seemingly unrelated events into a meaningful bigger picture.'],
            ['id'=>'q21','axis'=>'SN','dir'=> 1,'text'=>'When learning a new skill, you want to practice it right away rather than study the underlying theory first.'],
            ['id'=>'q22','axis'=>'SN','dir'=>-1,'text'=>'You often get pulled into "what if..." questions while you are in the middle of something else.'],
            ['id'=>'q23','axis'=>'SN','dir'=> 1,'text'=>'You pick a familiar, reliable tool over experimenting with a new one that promises more features.'],
            ['id'=>'q24','axis'=>'SN','dir'=>-1,'text'=>'You feel constrained when you have to follow a process that is too detailed and repetitive.'],

            ['id'=>'q25','axis'=>'TF','dir'=> 1,'text'=>'When a colleague presents a plan with flaws, you point them out immediately.'],
            ['id'=>'q26','axis'=>'TF','dir'=>-1,'text'=>'When a colleague presents a plan with flaws, you offer feedback gently to avoid discouraging them.'],
            ['id'=>'q27','axis'=>'TF','dir'=> 1,'text'=>'You believe sticking to a principle matters more than making an exception to spare someone\'s feelings.'],
            ['id'=>'q28','axis'=>'TF','dir'=>-1,'text'=>'You can bend a rule if doing so keeps the peace within the group.'],
            ['id'=>'q29','axis'=>'TF','dir'=> 1,'text'=>'In a debate, you are swayed by a sharp argument more than by a touching personal story.'],
            ['id'=>'q30','axis'=>'TF','dir'=>-1,'text'=>'It bothers you when someone speaks too bluntly and hurts another person in front of everyone.'],
            ['id'=>'q31','axis'=>'TF','dir'=> 1,'text'=>'Choosing between two candidates, you lean toward the one with a stronger track record, even if the other is more likable.'],
            ['id'=>'q32','axis'=>'TF','dir'=>-1,'text'=>'You often take a long time weighing a decision because you worry about how it might affect others negatively.'],
            ['id'=>'q33','axis'=>'TF','dir'=> 1,'text'=>'You judge an idea by its effectiveness and feasibility before considering whether it pleases everyone.'],
            ['id'=>'q34','axis'=>'TF','dir'=>-1,'text'=>'Hearing about someone\'s hardship, you easily picture yourself in their shoes and feel moved.'],
            ['id'=>'q35','axis'=>'TF','dir'=> 1,'text'=>'You find that speaking directly helps both sides understand each other faster, even if the words sting at first.'],
            ['id'=>'q36','axis'=>'TF','dir'=>-1,'text'=>'You are willing to step back in an argument to protect the relationship, even when you know you are right.'],

            ['id'=>'q37','axis'=>'JP','dir'=> 1,'text'=>'Before a trip, you prefer a clear day-by-day itinerary over leaving everything open-ended.'],
            ['id'=>'q38','axis'=>'JP','dir'=>-1,'text'=>'A weekend with nothing planned feels like a truly complete rest to you.'],
            ['id'=>'q39','axis'=>'JP','dir'=> 1,'text'=>'You usually finish assignments or projects early just to get them off your mind.'],
            ['id'=>'q40','axis'=>'JP','dir'=>-1,'text'=>'You produce your best work when the pressure of a deadline closes in at the last moment.'],
            ['id'=>'q41','axis'=>'JP','dir'=> 1,'text'=>'It bothers you when someone cancels a set plan at the last minute.'],
            ['id'=>'q42','axis'=>'JP','dir'=>-1,'text'=>'You easily change weekend plans when a more interesting option pops up unexpectedly.'],
            ['id'=>'q43','axis'=>'JP','dir'=> 1,'text'=>'You feel more at ease when everything in your workspace is in its designated spot.'],
            ['id'=>'q44','axis'=>'JP','dir'=>-1,'text'=>'You prefer keeping multiple options open at once rather than locking into one path early on.'],
            ['id'=>'q45','axis'=>'JP','dir'=> 1,'text'=>'You find it frustrating to work in an environment without clear processes.'],
            ['id'=>'q46','axis'=>'JP','dir'=>-1,'text'=>'Rigid rules feel like they stifle your creativity and adaptability.'],
            ['id'=>'q47','axis'=>'JP','dir'=> 1,'text'=>'You tend to make to-do lists and feel satisfied ticking off each completed item.'],
            ['id'=>'q48','axis'=>'JP','dir'=>-1,'text'=>'You often start your workday without a fixed list, handling whatever comes up as it arrives.'],
        ];
        $shuffled = $questions;
        shuffle($shuffled);
        return $shuffled;
    }

    public static function getProfiles(): array {
        static $profiles = null;
        if ($profiles !== null) return $profiles;

        $profiles = [
            'ENFP'=>[
                'title'     =>'The Campaigner',
                'short'     =>'Enthusiastic, creative, and always sees possibilities in people and ideas.',
                'overview' =>'You are drawn to new ideas, interesting people, and experiences you have not had before. You see the world through the lens of possibilities and connections. Your energy comes from exploring and sharing those discoveries with others.',
                'strengths' =>['Quickly connects with strangers','Sees potential where others overlook it','Adapts well to change','Naturally inspires people'],
                'weaknesses'  =>['Loses interest in repetitive tasks easily','Struggles to say no, takes on too much','Tends to postpone uninspiring work','Sometimes too optimistic, overlooking real risks'],
                'career' =>'You thrive in environments that value creativity and flexibility. Repetitive or rigid work drains your energy quickly. You do your best when free to experiment with new ideas and work alongside open-minded people.',
                'love'  =>'You look for alignment in core values and a partner willing to explore the world with you. You give your affection generously, but you may struggle to maintain a steady rhythm once the relationship becomes too familiar.',
            ],
            'ENTJ'=>[
                'title'     =>'The Commander',
                'short'     =>'Decisive, visionary, and has a natural ability to organize.',
                'overview' =>'You see the world as a system that can be optimized. You do not shy away from hard decisions and always lean toward forward motion. Others often look to you for direction when things become chaotic.',
                'strengths' =>['Clear strategic vision','Fast and decisive decision-making','Skilled at organizing people and resources','Not easily swayed by opposing opinions'],
                'weaknesses'  =>['Can come across as imposing and impatient with slower people','Sometimes overlooks feelings when pursuing goals','Struggles to accept failure or criticism','Prone to burnout from taking on too much responsibility'],
                'career' =>'You shine in leadership roles, project management, or running organizations. You need an environment large enough to challenge your vision. Positions without decision-making authority feel like a cage to you.',
                'love'  =>'You are not great at expressing feelings with words, but you show commitment through action and responsibility toward the relationship. You need a partner strong enough not to be overwhelmed, yet perceptive enough to hear what you leave unsaid.',
            ],
            'ENTP'=>[
                'title'     =>'The Debater',
                'short'     =>'Quick-witted, loves to debate, and endlessly pursues new ideas.',
                'overview' =>'You live in a world of ideas and possibilities. You enjoy taking a problem apart, turning it over from every angle, and questioning every assumption. To you, a debate is not conflict — it is how you learn.',
                'strengths' =>['Flexible thinker, quick with new problems','Unafraid to challenge the status quo','Skilled at spotting connections between unrelated fields','Bursting with creative energy when starting projects'],
                'weaknesses'  =>['Gets bored once a project moves into detailed execution','May argue just for the thrill of it, not to find a solution','Sometimes overlooks feelings when focused on logic','Struggles to maintain discipline with long-term habits'],
                'career' =>'You fit well in startups, strategy consulting, or anywhere that requires solving novel problems constantly. Repetitive tasks or excessive administrative procedures are a nightmare for you.',
                'love'  =>'You are drawn to people who can keep up with the speed of your thoughts. An intellectually stimulating conversation matters more to you than cliché romantic gestures. Your challenge is maintaining stability when the relationship enters a quieter phase.',
            ],
            'INTJ'=>[
                'title'     =>'The Architect',
                'short'     =>'Independent, deeply analytical, and has a clear long-term vision.',
                'overview' =>'You dislike ambiguity. You want to understand how things work and how to improve them. You are comfortable spending long stretches alone thinking, planning, and building systems. Noisy crowds are not where you find your energy.',
                'strengths' =>['Sharp analytical and strategic thinking','Highly effective when working independently','Skilled at long-term planning and anticipating risks','Steadfast in pursuit of chosen goals'],
                'weaknesses'  =>['Can appear cold and hard to approach','Sometimes too perfectionistic, delaying action until it meets the standard','Struggles to share feelings, easily mistaken for lacking care','Impatient with people who work inefficiently'],
                'career' =>'You are suited for fields that demand systems thinking such as strategy, research, technology, or planning. You work best with autonomy and space. Micromanagement will drive you out quickly.',
                'love'  =>'You do not open up easily, but once committed, you are fiercely loyal. You need a partner who understands that your silence is not a lack of care. You show love by solving problems for the person you care about, not through words.',
            ],
            'INTP'=>[
                'title'     =>'The Logician',
                'short'     =>'Curious, analytical, and always digging into the core of a problem.',
                'overview' =>'You spend a lot of time inside your own head — analyzing, questioning, and building models to understand the world. You do not care much for social rules if they do not make sense. To you, a good idea is worth more than a round of small talk.',
                'strengths' =>['Logical analysis and spotting flaws in arguments','Creative in building theories and solutions','Unmoved by peer pressure','Intellectually honest'],
                'weaknesses'  =>['Prone to overthinking to the point of inaction','Struggles to maintain regular social connections','May overlook both their own and others\' feelings','Impatient with inefficient processes'],
                'career' =>'You fit well in research, programming, data analysis, or any field that lets you explore ideas freely. Environments with too many meetings and procedures wear down your energy.',
                'love'  =>'You are not great at reading social signals and can sometimes come across as awkward in romantic matters. But you are sincere and have no taste for mind games. You need a partner who respects your personal space and does not expect romance to follow a script.',
            ],
            'INFJ'=>[
                'title'     =>'The Advocate',
                'short'     =>'Deep, empathetic, and always searching for meaning in everything.',
                'overview' =>'You live with a rich inner world that few people get to see. You sense other people\'s emotions almost as if they were your own. Shallow conversations do not interest you — you want to understand what is really going on beneath the surface.',
                'strengths' =>['Deep understanding of others','Long-term vision and ability to connect complex ideas','Steadfast in personal values','Gifted at helping others develop their potential'],
                'weaknesses'  =>['Prone to burnout from absorbing too many emotions from others','Tends toward perfectionism and harsh self-criticism','Hard to get close to, few truly know them','Easily wounded by conflict or criticism'],
                'career' =>'You find meaning in fields like counseling, education, the arts, or social work. You need a job aligned with your core values — without that, you will feel hollow even if everything on the surface looks successful.',
                'love'  =>'You long for a deep connection where both people truly see and understand each other. Casual relationships do not appeal to you. But you can get hurt if your partner cannot match the emotional depth you bring.',
            ],
            'INFP'=>[
                'title'     =>'The Mediator',
                'short'     =>'Sensitive, creative, and guided by a strong personal value system.',
                'overview' =>'You see the world through the lens of values and meaning. You care deeply about people and always want to do something that matters. Your calm exterior sometimes hides a fierce inner fire about the things you believe in.',
                'strengths' =>['Compassionate and deeply understanding','Creative in expressing ideas and emotions','Loyal to personal values','Open-minded and non-judgmental toward others'],
                'weaknesses'  =>['Easily wounded by criticism and conflict','Tends to idealize, then feels let down when reality falls short','Struggles to make decisions for fear of hurting others','Can get lost in negative emotions for extended periods'],
                'career' =>'You fit well in creative fields like writing, design, or the arts, as well as humanitarian work like counseling, education, or non-profits. You need to feel your work has meaning — money alone is not enough to keep you.',
                'love'  =>'You love deeply and sincerely, in the most genuine way. You place high hopes on the relationship and can feel disappointed when your partner does not live up to your ideals. You need someone who sees your inner world and treasures it.',
            ],
            'ENFJ'=>[
                'title'     =>'The Protagonist',
                'short'     =>'Warm, inspiring, and has a gift for bringing out the best in others.',
                'overview' =>'You seem to have a built-in antenna for reading other people\'s emotions and needs. You do not just understand them — you want to help them become the best version of themselves. This makes you a natural leader, even when you are not trying to be.',
                'strengths' =>['Outstanding ability to understand and connect with others','Inspires and motivates groups','Devoted and highly responsible toward those you lead','Skilled at mediating conflict and building consensus'],
                'weaknesses'  =>['Takes on others\' problems to the point of exhaustion','Tends to neglect personal needs','Struggles to accept when you cannot help someone','Sometimes prioritizes harmony over making tough decisions'],
                'career' =>'You shine in education, human resources, communications, or any role that lets you work directly with people. You need an environment that values human growth, not just numbers.',
                'love'  =>'You put a great deal of energy into the relationship and expect the same level of commitment in return. You are thoughtful and attentive to your partner\'s needs, but you sometimes forget that you need care too.',
            ],
            'ISTJ'=>[
                'title'     =>'The Logistician',
                'short'     =>'Disciplined, dependable, and guided by clear principles.',
                'overview' =>'You value facts, order, and reliability. When you commit to something, you see it through to the end. You dislike surprises and last-minute changes. People turn to you when they need someone who keeps their word.',
                'strengths' =>['Absolutely reliable, always delivers on commitments','Highly systematic and organized','Patient and meticulous with details','Makes decisions based on facts and logic'],
                'weaknesses'  =>['Rigid, struggles to adapt to sudden change','May miss the big picture by focusing too much on details','Finds it hard to express feelings, sometimes seen as cold','Struggles to accept methods that deviate from standard procedure'],
                'career' =>'You suit fields that demand high accuracy such as accounting, law, administration, or operations management. You work best in environments with clear processes and well-defined expectations.',
                'love'  =>'You are not the movie-style romantic type. You show love through stability, reliability, and practical daily actions. Your partner can rest assured that you will always be there when needed.',
            ],
            'ISFJ'=>[
                'title'     =>'The Defender',
                'short'     =>'Attentive, devoted, and quietly looks after those around them.',
                'overview' =>'You have a special ability to notice when someone needs help — often before they realize it themselves. You do not seek recognition for what you do. For you, taking care of others is simply a natural way of being.',
                'strengths' =>['Devoted and attentive to the smallest details','Remarkably good at remembering details about others','Patient and ready to support','Loyal and dependable in every relationship'],
                'weaknesses'  =>['Tends to take on too much without speaking up','Finds it hard to say no when others ask for help','Easily hurt when efforts go unnoticed','Wary of change and avoids conflict'],
                'career' =>'You fit well in healthcare, education, or customer service. You need a place where your dedication is appreciated and where you can see the direct impact of your work on people.',
                'love'  =>'You are the type of person who remembers their partner\'s favorite dish, anniversaries, and the small things others easily overlook. You need a partner who notices and values the quiet things you do, rather than taking them for granted.',
            ],
            'ESTJ'=>[
                'title'     =>'The Executive',
                'short'     =>'Practical, decisive, and skilled at turning plans into action.',
                'overview' =>'You believe in hard work, discipline, and doing your duty properly. You see clearly what needs to be done and do not hesitate to step up and take charge. To you, efficiency and measurable results matter more than abstract ideas.',
                'strengths' =>['Excellent at organizing and managing people','Hardworking and highly disciplined','Quick and decisive decision-making','Loyal to traditional values and commitments'],
                'weaknesses'  =>['Can appear rigid and stubborn','Finds it hard to stay flexible when plans need to change','Sometimes too focused on procedure, overlooking the human element','Impatient with those who lack discipline'],
                'career' =>'You suit management, executive, or supervisory roles, or any place that needs order established. You thrive in organizations with clear hierarchy and transparent evaluation criteria.',
                'love'  =>'You value honesty and stability in love. You are not one for sweet talk, but you build a solid foundation for the relationship. You need a partner who understands that your commitment shows itself through action.',
            ],
            'ESFJ'=>[
                'title'     =>'The Consul',
                'short'     =>'Sociable, caring, and skilled at bringing people together.',
                'overview' =>'You are the person people call when they need a gathering organized or simply someone to listen. You have a natural instinct for making others feel welcome. Harmony within the group is your priority.',
                'strengths' =>['Natural communicator, creates instant rapport','Highly attentive, remembers what matters to others','Skilled at organizing events and connecting people','Works hard to ensure everyone is looked after'],
                'weaknesses'  =>['Overly dependent on recognition and approval from others','Finds it hard to speak hard truths for fear of upsetting people','Tends to get too involved in other people\'s business','Easily hurt when efforts to connect are rejected'],
                'career' =>'You fit well in event planning, human resources, customer care, or education. You need an environment that values people skills and where you can see the social glue you create holding the group together.',
                'love'  =>'You invest a great deal of effort in caring for your partner and expect appreciation in return. You need verbal confirmation — silence makes you anxious. You shine brightest with someone who receives and returns affection openly.',
            ],
            'ISFP'=>[
                'title'     =>'The Adventurer',
                'short'     =>'Subtle, sensitive to beauty, and lives fully in each moment.',
                'overview' =>'You experience the world through your senses and emotions more than through analysis. You need few words to understand a work of art, a piece of music, or the mood of the person across from you. You live lightly and dislike imposing on others.',
                'strengths' =>['Aesthetically sensitive and naturally creative','Genuine, no pretense','Flexible and adapts easily to circumstances','Respects the space and freedom of others'],
                'weaknesses'  =>['Struggles with long-term planning','Easily wounded by criticism','Avoids confrontation and often retreats from conflict','May be misunderstood as uncaring because they express little verbally'],
                'career' =>'You suit creative fields like design, art, fashion, music, or any work that lets you express your personal taste. You need freedom and dislike being micromanaged.',
                'love'  =>'You express love through subtle gestures: a carefully chosen gift, a thoughtfully arranged experience. You are not great at talking about feelings, but you are excellent at creating moments both of you will remember.',
            ],
            'ISTP'=>[
                'title'     =>'The Virtuoso',
                'short'     =>'Calm, practical, and skilled at handling a crisis with action.',
                'overview' =>'You do not talk much, but your eyes are always observing. You understand how things work by taking them apart and putting them back together with your own hands. In a crisis, you are the one who stays calm and finds a practical solution while everyone else is still panicking.',
                'strengths' =>['Outstanding crisis handling','Practical and logical in problem-solving','Skilled with tools and technical work','Unswayed by emotions or social pressure'],
                'weaknesses'  =>['Struggles with emotional connection, easily seen as cold','Gets bored with long-term commitments','Not great at social communication and formalities','May overlook others\' feelings when focused on the solution'],
                'career' =>'You suit technical fields, mechanics, IT, or any job requiring hands-on skills and real-world problem solving. You like being free to work your own way.',
                'love'  =>'You dislike relationships that become too emotionally complicated. You need a partner who respects your independence and does not demand constant emotional expression. For you, love is about experiencing life together, not analyzing it together.',
            ],
            'ESTP'=>[
                'title'     =>'The Entrepreneur',
                'short'     =>'Bold, energetic, and skilled at seizing opportunities in a split second.',
                'overview' =>'You live in the present moment more fully than most. When an opportunity appears, you grab it. When a risk shows up, you handle it on the spot. You learn by doing, and you trust real results over theory. Life, to you, is a series of experiences to enjoy.',
                'strengths' =>['Quick reflexes in unexpected situations','Courageous in taking risks','Skilled at negotiation and persuasion','Charismatic and funny in social settings'],
                'weaknesses'  =>['Prone to impulsive action without calculating consequences','Finds it hard to stay patient with long-term projects','May overlook others\' feelings when chasing a goal','Not great at planning, gets bored with routines'],
                'career' =>'You shine in business, sales, sports, or any fast-paced environment that demands instant reaction. Desk jobs with repetitive tasks do not suit you.',
                'love'  =>'You are the attractive, fun type who always brings surprises. But you also get restless easily. You need a partner who understands your need for freedom and is ready to join the adventure, rather than trying to hold you back.',
            ],
            'ESFP'=>[
                'title'     =>'The Entertainer',
                'short'     =>'Cheerful, spontaneous, and spreads positive energy everywhere.',
                'overview' =>'You walk into a room and the atmosphere changes. You have the ability to make people laugh, make them feel comfortable, and turn ordinary moments into memorable ones. For you, life is meant to be experienced and shared.',
                'strengths' =>['Naturally magnetic and positive energy','Skilled at adapting and improvising in any social situation','Generous with time and affection','Lives fully in the present'],
                'weaknesses'  =>['Struggles with long-term planning, tends to procrastinate','May depend too heavily on attention from others','Easily bored, constantly seeks new stimulation','Finds it hard to face serious problems that require deep thought'],
                'career' =>'You fit well in entertainment, media, hospitality, or any field where you interact with people and bring joy. Isolated work or excessive paperwork drains you dry.',
                'love'  =>'You love with your whole heart and want every day together to be a beautiful memory. You need a partner who appreciates your warmth but also helps you slow down sometimes and think about the future, not just live for today.',
            ],
        ];

        return $profiles;
    }
}