<?php

if (!defined('ABSPATH')) exit;

return [
    '__meta' => [
        'schema_version' => '4.0.1',
        'dataset_type' => 'architectural_nodes',
        'updated_at' => '2026-04-14',
        'scope' => 'full_data_driven_dataset',
    ],
    'hint' => [
        0 => [
            'negative'       => '{pressure from multiple directions at once|a multidimensional challenge requiring broad development|no single barrier, but demands strong self-direction}',
            'short_negative' => 'combined pressure',
            'advice'         => '{learn to work through your own resistance, get clear on direction|build personal discipline and set your own goals|own every decision, stop leaning on others}',
        ],
        1 => [
            'core'     => '{independent, pioneering, self-directed|initiating, decisive, self-determined|a natural leader who pushes past limits}',
            'action'   => '{decisive, bold, drawn to leading|confident, proactive, willing to take risks|strong, expresses itself clearly and independently}',
            'inner'    => '{craves victory and recognition|wants to prove itself and take charge of its own life|needs independence, wants to show who it really is}',
            'advice'   => '{learn to listen, slow down, soften the ego|balance confidence with humility|stop imposing your views, respect other perspectives}',
            'negative' => '{high ego, controlling, impulsive|rigid, impatient, pushes its agenda|self-absorbed, domineering, poor listener}',
            'period'   => '{a fresh start, time to plant seeds and move independently|a moment to break through, clear a path, and take the lead|a pioneering window, establish new footing}',
            'lesson'   => '{confidence, independence, and the ability to decide for yourself|learning to lead yourself before leading others|build personal courage, step up when it counts}',
        ],
        2 => [
            'core'     => '{mediating, connecting, empathetic|brings calm, builds harmony|listens deeply, holds people together}',
            'action'   => '{listens, cooperates, moves gently|perceptive, tactful, reads the room|peaceful, understanding, values consensus}',
            'inner'    => '{craves love, peace, and companionship|wants closeness, fears loneliness|seeks harmony and to understand what others feel}',
            'advice'   => '{learn to decide on your own, rely less on how others make you feel|practice independence, stop over-accommodating|protect your boundaries, trust your gut}',
            'negative' => '{overly sensitive, easily hurt, wishy-washy|hesitant, avoids conflict, fears disappointing others|emotionally dependent, thrown off by outside events}',
            'period'   => '{a time for waiting, cooperating, and strengthening bonds|patience, connection, and genuine empathy are the focus|a stage for developing intuition and keeping the peace}',
            'lesson'   => '{patience, the ability to listen, and real empathy|learning to cooperate and manage emotions|develop sensitivity and the ability to balance relationships}',
        ],
        3 => [
            'core'     => '{creative, inspiring, radiant|spreads joy through art and expression|lively, imaginative, naturally positive}',
            'action'   => '{upbeat, funny, draws people in through conversation|expresses itself freely, has a way with words|enthusiastic, connects easily}',
            'inner'    => '{wants to express itself and make people laugh|craves attention, freedom to show emotion|wants to use words to move and inspire people}',
            'advice'   => '{learn to manage emotions and stay focused on goals|stop scattering energy, work with a plan|watch what you say, develop more depth}',
            'negative' => '{unfocused, emotionally erratic, skims the surface|talks more than acts, scattered, gets bored fast|impulsive, easily swayed, lacks follow-through}',
            'period'   => '{a shining stage, chances to expand communication and create|a burst of ideas, time to spread joy|a social, expressive phase}',
            'lesson'   => '{how to express emotion, stay optimistic, and create|learning to focus and use words well|develop aesthetic instincts and confidence in front of others}',
        ],
        4 => [
            'core'     => '{building, stable, grounded|establishes order, structure, and discipline|reliable, consistent, operates by clear processes}',
            'action'   => '{disciplined, thorough, dependable|works systematically, attentive to detail|practical, principled, puts safety first}',
            'inner'    => '{craves security, order, and clarity|wants everything planned and settled|looks for solid ground, avoids risk}',
            'advice'   => '{learn to bend, loosen the rigid thinking|open up to new things, stop pressuring yourself|balance work with rest}',
            'negative' => '{inflexible, slow to change, overly cautious|stubborn, fixated on detail, conservative|struggles with spontaneity, easily stressed by rules}',
            'period'   => '{building a stronger foundation, working steadily, reorganizing|a time to establish order, discipline, and real-world results|a stage of constructing something durable, built to last}',
            'lesson'   => '{building a solid foundation and real discipline|patience, organization, and staying practical|develop persistence and a methodical work style}',
        ],
        5 => [
            'core'     => '{freedom, experience, discovery|adapts fast, breaks through, loves to move|dynamic, flexible, always drawn to what is new}',
            'action'   => '{flexible, quick to adapt, full of energy|sharp, curious, thinks and acts boldly|ready to pivot, seizes opportunities fast}',
            'inner'    => '{craves adventure, change, and resists being boxed in|wants varied experiences and complete freedom|fears boredom, constantly chases stimulation}',
            'advice'   => '{learn to commit, manage risk, and set limits|practice patience, stop dropping things the moment they get routine|set clear goals and stick to them}',
            'negative' => '{unstable, easily bored, impulsive|undisciplined, easily distracted, changes course too often|avoids commitment, gives up halfway}',
            'period'   => '{major change, a chance to break through and expand|time for travel, freedom, and new opportunities|a phase of breaking old habits and staying adaptable}',
            'lesson'   => '{adaptation, handling freedom, and the courage to change|learning to focus and follow through|develop the skill to improvise without losing direction}',
        ],
        6 => [
            'core'     => '{responsibility, care, love|nurturing, harmonious, family-centered|tolerant, protective, drawn to beauty}',
            'action'   => '{tolerant, supportive, brings warmth|dedicated, thoughtful, always ready to help|attentive, keeps others in mind}',
            'inner'    => '{craves a home, harmony, and beauty|wants to give to family and loved ones|seeks peace, avoids conflict}',
            'advice'   => '{learn to love yourself, let go of controlling others|respect people\'s space, stop taking on everything|release responsibilities that were never yours to carry}',
            'negative' => '{overextends, controlling, sacrifices too much|smothers with love, worries constantly|meddles in others\' lives, self-righteous}',
            'period'   => '{turning toward family, fulfilling responsibilities, giving love|a time to tend to home and deepen relationships|maintaining harmony and supporting the people closest to you}',
            'lesson'   => '{responsibility and tolerance in relationships|learning to balance giving and receiving|develop unconditional love}',
        ],
        7 => [
            'core'     => '{intellect, analysis, depth|contemplation, stillness, searching for truth|research, philosophy, trusts lived experience}',
            'action'   => '{private, observant, calm and measured|analyzes thoroughly, thinks things through|prefers quiet, independent in thought}',
            'inner'    => '{seeks truth, knowledge, and stillness|wants to understand the nature of things|wants privacy, values spiritual development}',
            'advice'   => '{learn to open up, stop withdrawing and being cynical|share what you know, reconnect with the real world|stop overthinking, trust your intuition}',
            'negative' => '{isolates itself, cold, suspicious|closed off, self-satisfied with its knowledge, hard to reach|overly analytical, prone to cynicism and dark moods}',
            'period'   => '{turning inward, studying, growing spiritually|a time to reflect, research, and sharpen the mind|re-evaluating yourself, searching for what is true}',
            'lesson'   => '{trust in yourself, building knowledge and real depth|learning to be more open and less suspicious|develop both intuition and analytical thinking}',
        ],
        8 => [
            'core'     => '{power, achievement, vision|management, confidence, aims for prosperity|practical, financially independent, executes well}',
            'action'   => '{confident, decisive, practically focused|proactive, spots business opportunities|works professionally, keeps results in sight}',
            'inner'    => '{craves success, financial independence, authority|wants to master the game and build real wealth|seeks recognition through achievement}',
            'advice'   => '{balance material and spiritual, avoid being purely transactional|know when enough is enough, keep ethics in your business|use power to lift others, not just to advance yourself}',
            'negative' => '{overly ambitious, domineering, material-obsessed|cold, pragmatic, abuses power|puts personal gain above everything, dictatorial}',
            'period'   => '{reaping what you\'ve built, managing finances, advancing|a time to focus on career and authority|a harvest phase of business and execution}',
            'lesson'   => '{financial management, confidence, and independence|learning to balance money and ethics|develop leadership and risk management skills}',
        ],
        9 => [
            'core'     => '{humanitarian, devoted, idealistic|selfless, wide perspective, serves the community|tolerant, does good, works on itself}',
            'action'   => '{generous, tolerant, always ready to help|gives without expectation, acts for the greater good|aims for shared benefit, spreads real inspiration}',
            'inner'    => '{wants to help the world and improve both itself and its community|craves a better world, tends to idealize|wants to leave something truly meaningful behind}',
            'advice'   => '{learn to let go, stop chasing illusions and taking on too much|accept reality, stop demanding perfection from everything|help others but protect yourself too}',
            'negative' => '{carries heavy emotions, idealizes, clings to the past|grandiose delusions, easily taken advantage of|let down by its own high expectations, sacrifices pointlessly}',
            'period'   => '{closing a cycle, clearing out, transitioning, and forgiving|letting go of the past and moving toward something more humane|a phase of completion, service, and inner purification}',
            'lesson'   => '{selflessness, letting go, and a humanitarian perspective|learning to give without keeping score|develop a meaningful philosophy and deep empathy}',
        ],
        11 => [
            'core'     => '{sharp intuition, spiritual, inspiring|deep empathy, a messenger of sorts|awakened, sensitive, operates on a higher awareness}',
            'action'   => '{delicate, deeply empathetic, radiates energy|inspires through both words and action|listens to its inner voice, acts from intuition}',
            'inner'    => '{craves enlightenment and deeper meaning|wants spiritual connection, wants to understand how things work|seeks peace within itself}',
            'advice'   => '{keep your nervous system balanced, stop feeding anxiety|trust your intuition, learn to quiet your mind|set emotional limits before you burn out}',
            'negative' => '{constant anxiety, too sensitive, emotionally off-balance|easily overwrought, pulled toward negative thinking|dreamy, impractical, gets hurt easily}',
            'period'   => '{a spiritual awakening, strong intuitive signals|a time to inspire and develop awareness|a sensitive stage that needs emotional steadiness}',
            'lesson'   => '{trust your intuition, accept your spiritual path|learning to balance emotion and reality|develop both empathy and the ability to inspire}',
        ],
        22 => [
            'core'     => '{builds on a large scale, turns vision into reality|a master builder, organizes at scale|strategic vision backed by strong execution}',
            'action'   => '{executes powerfully, sees the big picture, organizes well|deliberate actions, builds lasting foundations|operates at scale with iron discipline}',
            'inner'    => '{craves leaving a lasting legacy|wants to bring ambitious ideas to life|seeks to build something that outlasts the moment}',
            'advice'   => '{stop piling pressure on yourself|share the load, learn to delegate|pair big-picture thinking with concrete day-to-day steps}',
            'negative' => '{self-imposed pressure is crushing, rigid, can\'t delegate|conservative, overworked, enforces strict rules|prone to stress and extreme ambition}',
            'period'   => '{building a large foundation, creating lasting projects|a time to execute major plans|a stage that demands systemization and sustained focus}',
            'lesson'   => '{balancing a big vision with practical daily action|learning to cooperate and share the vision|develop the skills to manage large-scale projects}',
        ],
        33 => [
            'core'     => '{heals broadly, loves unconditionally|deep compassion, willing to sacrifice for others|lifts spirits, a master of empathy}',
            'action'   => '{sacrifices, selfless, lifts those around it|spreads love, supports without conditions|ready to take on others\' pain}',
            'inner'    => '{craves to serve and heal|wants to bring peace to the world|finds meaning through giving and sacrifice}',
            'advice'   => '{protect your energy, stop carrying what isn\'t yours|learn to say no, take care of yourself first|heal others without losing yourself in the process}',
            'negative' => '{crushed by emotional weight, sacrifices too much, exhausted|easily exploited, loses itself for others|takes on too much, suffers for others\' pain}',
            'period'   => '{immense love, serving the community|a time of forgiveness, healing, and support|a phase of spreading compassionate energy widely}',
            'lesson'   => '{love yourself as much as you love others|learning where sacrifice ends and self-destruction begins|develop the ability to heal without getting tangled in it}',
        ],
        13 => [
            'negative' => '{procrastination, laziness, dodges responsibility|lacks discipline, gives up easily, avoids hard things|works on the surface, never sees things through}',
            'advice'   => '{build real discipline, work hard, push through difficulty|practice persistence, focus on small consistent steps|commit to finishing what you start}',
        ],
        14 => [
            'negative' => '{loses control, chases pleasure, can\'t resist temptation|inconsistent, easily pulled off course, lives loosely|erratic, breaks commitments}',
            'advice'   => '{restrain yourself, commit for the long term, balance freedom with structure|set limits, control momentary urges|build self-discipline, stop living impulsively}',
        ],
        16 => [
            'negative' => '{arrogant, prone to collapse, isolates itself|self-absorbed, delusional about its own strength, easily wounded inside|rigid, can\'t admit mistakes, closed off}',
            'advice'   => '{practice humility, wake up spiritually, learn to let go|accept that things fall apart so you can rebuild yourself|expand tolerance, stop judging so harshly}',
        ],
        19 => [
            'negative' => '{selfish, abuses power, ends up alone|only thinks of itself, manipulates people|disregards others entirely, refuses help}',
            'advice'   => '{respect others, learn to cooperate and share|use strength to protect, not to dominate|listen, stay humble, be open to receiving support}',
        ],
        15 => [
            'action'   => '{tolerant and caring, but actively so and genuinely flexible|loves freely, without putting conditions on it|enthusiastic in support, willing to change to meet people where they are}',
        ],
    ],
    'archetypes' => [
        1 => [
            'display' => '1',
            'name' => 'Pioneer',
            'light' => 'proactively paves the way',
            'shadow' => 'ego too strong',
        ],
        2 => [
            'display' => '2',
            'name' => 'Peacemaker',
            'light' => 'empathy and connection',
            'shadow' => 'hesitant or overly sensitive',
        ],
        3 => [
            'display' => '3',
            'name' => 'Expresser',
            'light' => 'creative and inspiring',
            'shadow' => 'scattered or all talk no action',
        ],
        4 => [
            'display' => '4',
            'name' => 'Foundation',
            'light' => 'disciplined and persistent',
            'shadow' => 'rigid or overly self-pressuring',
        ],
        5 => [
            'display' => '5',
            'name' => 'Freedom',
            'light' => 'flexible and adaptable',
            'shadow' => 'scattered or easily bored',
        ],
        6 => [
            'display' => '6',
            'name' => 'Responsibility',
            'light' => 'caring and harmonious',
            'shadow' => 'overbearing or overly controlling',
        ],
        7 => [
            'display' => '7',
            'name' => 'Contemplator',
            'light' => 'depth and analysis',
            'shadow' => 'withdrawn or cynical',
        ],
        8 => [
            'display' => '8',
            'name' => 'Manager',
            'light' => 'brave and results-driven',
            'shadow' => 'overly controlling or achievement-heavy',
        ],
        9 => [
            'display' => '9',
            'name' => 'Server',
            'light' => 'broad vision and selfless',
            'shadow' => 'overly idealistic or hard to let go',
        ],
        11 => [
            'display' => '11/2',
            'name' => 'Master Intuition',
            'light' => 'intuition and inspiration',
            'shadow' => 'overloaded by high sensitivity',
        ],
        22 => [
            'display' => '22/4',
            'name' => 'Master Builder',
            'light' => 'large-scale building',
            'shadow' => 'overbearing or pressure of responsibility',
        ],
        33 => [
            'display' => '33/6',
            'name' => 'Master Healer',
            'light' => 'love and healing',
            'shadow' => 'excessive sacrifice',
        ],
    ],
    'attitude' => [
        1  => 'Carries a pioneering quality. When facing something unfamiliar, tends to step up and find the way forward rather than wait for someone else to.',
        2  => 'Emotional warmth and a genuine ability to sense what others feel create a sense of closeness from early on.',
        3  => 'Positive energy and natural expression tend to make the atmosphere around them more alive.',
        4  => 'Approaches everything with certainty. Prioritizes stability and moves step by step on solid ground.',
        5  => 'Adapts quickly and moves freely. Naturally gravitates toward new experiences and keeps things in motion.',
        6  => 'Care for the people closest to them shows up early in relationships and responsibilities.',
        7  => 'Tends to observe and sense the deeper layers of a situation rather than react to what is immediately visible.',
        8  => 'A decisive spirit and a drive to establish personal value show clearly in how they act.',
        9  => 'A broad perspective and genuine empathy strongly shape how they see life and what they choose to do.',
        11 => 'Sharp intuition and the ability to pick up on what isn\'t said creates a particular kind of attunement to the world.',
        22 => 'Builds things with longevity in mind and tends to keep the larger purpose in view behind every choice.',
        33 => 'A healing quality and real tolerance tend to define how they connect with people.',
    ],
    'birthday' => [
        1  => 'A decisive and independent nature creates a tendency to find their own way in important choices.',
        2  => 'Sensitivity and empathy make connections feel easy and natural, the kind that build trust without effort.',
        3  => 'Natural expression brings creative energy and a clearly optimistic tone.',
        4  => 'Practical thinking and discipline build the base for values that actually hold up over time.',
        5  => 'A craving for freedom and flexible instincts keep the spirit fresh through change.',
        6  => 'A sense of responsibility and genuine care tie closely to family and community.',
        7  => 'A sharp intellect that leans toward observation and analysis, always trying to get at what something really means.',
        8  => 'Executive ability and management thinking turn available resources into concrete outcomes.',
        9  => 'A strong sense of ideals tends to point toward human values and service on a wide scale.',
        10 => 'Starting energy that tends toward reinvention and breaking out of old patterns.',
        11 => 'Sharp intuition picks up subtle signals and carries real inspiring power.',
        12 => 'A combination of creative thinking and genuine enthusiasm that executes ideas with a sense of responsibility.',
        13 => 'Results come through persistence and discipline. Challenges become steps rather than walls.',
        14 => 'Freedom and structure intertwine. This opens a balanced way of living between experience and commitment.',
        15 => 'Natural charm and a persuasive quality help build standing and social influence.',
        16 => 'A life path tied to inner transformation, moving toward awakening and new understanding.',
        17 => 'Strong ambition paired with intellectual depth produces achievements built on solid values.',
        18 => 'A leadership capacity that comes through when personal authority meets a genuinely selfless spirit.',
        19 => 'The lesson of self-reliance builds inner strength that eventually becomes a foundation for others.',
        20 => 'Awareness of context and skillful diplomacy keeps relationships in balance.',
        21 => 'Positive energy and openness tend to attract joy and support from others.',
        22 => 'The stature of a builder, with a real capacity to bring large-scale projects into existence.',
        23 => 'Quick adaptation and sharp thinking help navigate new situations without losing footing.',
        24 => 'A dedicated spirit creates reliability and stable rhythms across many areas of life.',
        25 => 'Where logic and intuition meet, clarity about the surrounding world tends to follow.',
        26 => 'A coordinating ability that makes good use of resources to reach shared goals effectively.',
        27 => 'Wide knowledge and a kind disposition build genuine respect and depth.',
        28 => 'Personal strength paired with a cooperative spirit tends to produce real career breakthroughs.',
        29 => 'A rich inner world and sincere ideals drive a search for balance.',
        30 => 'Language and communication are where their personal mark shows most clearly.',
        31 => 'A self-reliant spirit combined with organized thinking helps them walk steadily on practical paths.',
    ],
    'life_path' => [
        1  => 'This path carries a trailblazing quality. Independence and decisiveness leave a distinct mark. The ego needs managing to stay genuinely connected with others.',
        2  => 'This energy leans toward harmony and connection. Intuition is sharp in relationships. Building decisiveness prevents getting stuck in hesitation.',
        3  => 'A path of creativity and inspiration. A personal voice that travels easily to others. Focus keeps ideas from floating away.',
        4  => 'This path builds on discipline and persistence. It creates a foundation for lasting values. Flexibility prevents the pace from becoming too rigid.',
        5  => 'This energy ties to movement, experience, and constant change. A steady mindset handles distraction and fast boredom.',
        6  => 'This mark leans toward care, protection, and keeping relationships smooth. Clear limits prevent taking on too much or holding on too tightly.',
        7  => 'This path goes deep into contemplation and knowledge. Inner strength forms through quiet observation. Softening the tendency to close off allows real clarity to emerge.',
        8  => 'This energy aims for specific achievements and resource coordination. Ambition only holds when paired with balance and restraint.',
        9  => 'A path of kindness and wide vision, focused on values larger than the self. Releasing expectations keeps the mind clear and light.',
        11 => 'Strong intuition and sensitive awareness create a particular channel of perception. Inner stability is what lets this energy actually shine.',
        22 => 'Carries a builder quality. This energy fits large work and long-term vision. The weight of responsibility eases when the pace stays steady and sustainable.',
        33 => 'A vibration of love and healing, carrying a clear supportive strength. When giving goes hand in hand with self-care, this energy shines more.',
    ],
    'destiny' => [
        1  => 'The path aims toward a pioneering role. An independent will and a trailblazing spirit leave a distinctive mark.',
        2  => 'Energy that fits connection and reconciliation. Uses sensitivity to keep relationships balanced.',
        3  => 'Expression and creativity stand out. Brings inspiration and positive color to those nearby.',
        4  => 'A path tied to building a solid foundation. Turns ideas into reality through persistence and stability.',
        5  => 'Freedom and experience open toward innovation. Always searching for a different angle on life.',
        6  => 'Energy that leans toward love and care. Often plays the role of creating warmth and connection.',
        7  => 'A path toward contemplation and deep knowledge. Clarity comes through looking inward.',
        8  => 'Coordination and resource management help this path reach material achievement and stability.',
        9  => 'A humane spirit and selflessness act as a compass for how people and life are seen.',
        11 => 'Strong intuition and sensitive perception create a role in inspiring and awakening awareness.',
        22 => 'A building energy that stands out for turning big ideas into lasting value.',
        33 => 'A vibration of healing and tolerance that often brings peace to those around it.',
    ],
    'soul' => [
        1  => 'The drive for autonomy and asserting a place in the world fuels deep inner satisfaction.',
        2  => 'Inner peace arrives when there is room for sharing, understanding, and genuine harmony.',
        3  => 'Motivation runs highest when freely expressing creativity and spreading joy.',
        4  => 'Peace of mind ties to a clear plan and values that hold up in the real world.',
        5  => 'A craving for discovery and free experience keeps life from ever feeling flat.',
        6  => 'Life feels most meaningful through love and the bonds that go deep.',
        7  => 'A quiet mind and the need to find the truth create a kind of intellectual balance.',
        8  => 'Pride in real, visible achievements and management ability builds the foundation of confidence.',
        9  => 'Deep happiness comes through contributing to human values and genuine ideals.',
        11 => 'A sharp inner world and strong intuition push toward deeper spiritual layers.',
        22 => 'A drive to build something significant and bring visions into reality is a standout motivation.',
        33 => 'Fulfillment comes from spreading compassion and bringing a sense of healing to others.',
    ],
    'personality' => [
        1  => 'Projects an independent, strong quality. Always ready to take the lead.',
        2  => 'A gentle manner and receptive attitude create a warm, approachable feeling from the start.',
        3  => 'A confident style and engaging conversation highlight creativity and positive energy.',
        4  => 'Neatness, solidity, and practicality stand out and build genuine reliability.',
        5  => 'Free, dynamic energy and flexible adaptation show clearly against changing circumstances.',
        6  => 'A mark of dedication, warmth, and care for harmony leaves an easy-to-like impression.',
        7  => 'Calm with a slight air of mystery, and a sharp mind that creates real intellectual depth.',
        8  => 'A successful, decisive style and strong management ability come through clearly.',
        9  => 'An image tied to kindness, broad perspective, and a composed presence.',
        11 => 'Delicate presence and a particular kind of sharpness create a genuinely inspiring quality.',
        22 => 'The look of a steady strategist. Creates trust when building things at scale.',
        33 => 'A genuine tolerance and healing energy create a kind and quietly commanding image.',
    ],
    'maturity' => [
        1 => 'Maturity Number 1 reflects a growth trend toward independent leadership. Experience and awareness shape how that plays out.',
        2 => 'In Maturity Number 2, growth ties to the ability to create harmony. Sensitivity gets channeled with more intention.',
        3 => 'With Maturity Number 3, the work is on refining expression. Communication and creativity become clearer and carry more weight.',
        4 => 'Maturity Number 4 shows a trend of building stable ground. Discipline and structure become more deliberate.',
        5 => 'The growth arc of Maturity Number 5 revolves around widening experience while keeping direction and self-control.',
        6 => 'Maturity Number 6 ties to deepening responsibility, particularly in relationships and caregiving roles.',
        7 => 'In Maturity Number 7, growth moves inward. Observation, reflection, and understanding the core of things become the priority.',
        8 => 'Maturity Number 8 focuses on organization and management. Resources get used with more efficiency and purpose.',
        9 => 'Maturity Number 9 reflects an expanding awareness of shared values and a pull toward broader contribution.',
        11 => 'Maturity Number 11/2 shows intuition developing at a high level, along with a deepening sensitivity and awareness.',
        22 => 'With Maturity Number 22/4, building capacity rests on systematic thinking and a growing ability to actualize.',
        33 => 'Maturity Number 33/6 relates to the capacity to support and heal, expressed through a calm and responsible approach.',
    ],
    'balance' => [
        1 => 'Independence and self-direction act as the main anchor. When things shift, taking back control quickly restores stability.',
        2 => 'Listening and empathy regulate the emotional rhythm. Genuine connection with others smooths the pace of life.',
        3 => 'Optimistic thinking and creative expression naturally relieve pressure. Sharing ideas or finding new inspiration lightens the mind.',
        4 => 'Practicality and discipline build a solid base. Regaining calm comes from reorganizing and focusing on what can be controlled.',
        5 => 'Curiosity and flexibility help navigate hidden dead ends. Changing the environment or perspective brings fresh energy.',
        6 => 'A sense of responsibility and care for family and community keeps things grounded. Harmony in close relationships brings peace of mind.',
        7 => 'Private space for deep thinking and analysis is necessary. Balance comes through learning, observing, and understanding what is actually going on.',
        8 => 'Decisive action and practical control keep the mindset steady. Specific goals and clear results bring a high degree of stability.',
        9 => 'A tolerant view and an upward orientation ease internal conflict. Selflessness and a spirit of service bring a lighter state.',
        11 => 'Sharp intuition combined with genuine calm anchors the mental axis. Sensitive awareness and spiritual inspiration make the path clearer.',
        22 => 'Systematic thinking and large-scale execution control the situation. Building lasting value for others keeps the foundation solid.',
        33 => 'Compassion and the capacity to heal act as the roots of harmony. Spreading love and supporting others quiets the internal state.',
    ],
    'rational_thought' => [
        1 => 'Independence and decisiveness show clearly in thinking. Often finds a separate path and prioritizes autonomy and leadership when facing a situation.',
        2 => 'Approaches problems through empathy and listening. Thinking aims for harmony, looks for common ground, and tries to balance all sides.',
        3 => 'Rich imagination and flexible thinking create many open directions. Solutions tend to come from sudden creativity, paired with engaging communication.',
        4 => 'Strong in logic, practicality, and orderly thinking. Reasoning relies on concrete facts, favors safe options, and works best with clear roadmaps.',
        5 => 'Sharp thinking and quick redirection adapt to change. Problem-solving leans toward seeing things from multiple angles, ready to try something new to find what actually fits.',
        6 => 'Thinking weighs responsibility and stability heavily. Decisions tend toward family or community, with care and harmony as the guiding concerns.',
        7 => 'Thinking leans toward research and careful observation. Does not rush to conclusions. Takes time to reflect and peel back layers before reaching the core.',
        8 => 'Strongly focused on practical efficiency and specific goals. Views things strategically, optimizes resources for clear and durable results.',
        9 => 'A wide perspective and humanitarian ideals stand out. Thinking skips minor details to focus on shared values and broader benefit.',
        11 => 'Intuitive sensitivity works alongside sharp mental awareness. Tends to grasp hidden meaning and offer insights that open things up.',
        22 => 'Large-scale thinking paired with strong implementation ability. Takes complex ideas and organizes them into plans that can actually be applied.',
        33 => 'Compassion and understanding form the main axis of thought. Views life with a sense of spiritual responsibility, leaning toward lifting others.',
    ],
    'subconscious_self' => [
        1 => 'The need for autonomy and leadership sits at the core of the subconscious. When that is restricted, direction becomes unclear and the drive to act drains away.',
        2 => 'Mental strength comes from connection and genuine understanding of others. A lack of harmony or ongoing conflict drains motivation significantly.',
        3 => 'Free expression and creativity are the most alive parts of the self. When ideas go unacknowledged or there is no space to develop them, a sense of being trapped rises quickly.',
        4 => 'Peace of mind ties to order and staying with goals that have been set. Unstructured environments or broken plans produce anxiety and erode endurance.',
        5 => 'A craving for novelty and varied experience drives core psychology. Feeling locked into rigid frameworks kills adaptability and sharpness.',
        6 => 'Readiness to support others and build harmony is the core energy. Failing to play a caring role or encountering discord shakes the mental state.',
        7 => 'A deep pull toward truth and gathering knowledge is a hidden instinct. Being forced to accept shallow information triggers a strong resistance.',
        8 => 'Asserting personal value through real outcomes guides thinking. When effort fails to produce something visible, a sense of lost control follows.',
        9 => 'Service to the community and tolerant ideals root all behavior. When work or life lacks human meaning, the hidden motivation dims.',
    ],
    'personal_year' => [
        1 => 'Opens a new cycle with autonomy and decisive energy. A key time to set personal goals, take independent steps, and build the premise for the next nine years.',
        2 => 'The focus shifts to patience and working well with others. This year calls for sharp listening, building lasting relationships, and finding balance across all areas of life.',
        3 => 'A burst of creative thinking and expression. Expanding social connections, spreading ideas, and finding fresh inspiration make life genuinely lively.',
        4 => 'A time to strengthen foundations and establish order. Persistence, discipline, and attention to real-world details build a solid structure for what comes next.',
        5 => 'A year of fluctuation and real-world experience. Adapting flexibly to new opportunities breaks through old barriers and creates genuinely valuable turning points.',
        6 => 'Family responsibilities and community commitments move to the top. Nurturing relationships, showing dedication, and building a harmonious environment bring inner peace.',
        7 => 'A year for deep reflection and developing the intellect. The time to quiet down, examine past lessons, study seriously, and build mental strength.',
        8 => 'A stage for reaping what has been built, backed by executive ability and strategic thinking. Decisiveness in managing resources and a focus on performance establish standing and stability.',
        9 => 'Closes the old cycle with tolerance and a spirit of service. Filtering out what no longer fits and completing unfinished business prepares the mind for a new beginning.',
        11 => 'Sharp intuition and heightened awareness become the compass for everything. This year pushes toward exploring deeper values and creating positive influence through inspiration.',
        22 => 'A time to actualize systematic and large-scale plans. Combining wide vision with strong execution creates achievements with real and lasting social value.',
        33 => 'The focus turns to compassion and healing. Spreading understanding, supporting the community, and living by genuine humanist ideals bring real harmony and joy.',
    ],
    'personal_month' => [
        1 => 'A month of fresh starts and independent action. Rolling out new ideas, taking ownership, and completing personal goals are the focus.',
        2 => 'A month for connection and harmony. Listen carefully, build trust in relationships, and work through problems by cooperating rather than pushing.',
        3 => 'A burst of creative thinking and communication. Spread ideas, expand social connections, and use inspiration to refresh daily activities.',
        4 => 'A month focused on order and staying consistent. Review the details, set up structure, and execute with genuine discipline and responsibility.',
        5 => 'A month of changes and flexible adaptation. Break through old patterns, try new paths with confidence, and use unexpected opportunities to shift direction.',
        6 => 'A month oriented toward family responsibility and harmony. Nurture relationships, care for the people closest to you, and build a balanced living environment.',
        7 => 'A month to look inward and deepen knowledge. Learn, get to the bottom of things, and use quiet time to reassess where development is heading.',
        8 => 'A month for asserting executive ability and practical performance. Manage resources well, optimize results, and produce something tangible.',
        9 => 'A month of completion and letting go. Finish what has been sitting unfinished and clear out what no longer fits, to prepare for the next phase.',
        11 => 'A month of subtle awareness and sharp intuition. Understand what actually matters, catch hidden opportunities, and stay calm through everything.',
        22 => 'A month to deploy systematic plans with a long-term view. Use organizational ability to build solid foundations with lasting practical value.',
        33 => 'A month of compassion and community support. Spread kindness, help resolve conflicts, and create harmony in every interaction.',
    ],
    'personal_day' => [
        1 => 'A day for beginnings and independent decisions. Catch new opportunities, deploy personal plans with confidence, and take charge of situations.',
        2 => 'A time for listening and harmony. Prioritize collaboration, mutual support, and finding genuine connection in daily conversations.',
        3 => 'A day of ideas and open communication. Share, show what you can create, and build a positive atmosphere for relationships.',
        4 => 'A day that rewards neatness and practical effort. Finish pending tasks through discipline and careful attention to detail.',
        5 => 'A day for new experiences and flexibility. Be ready to adjust, welcome surprises, and find different ways to get things done.',
        6 => 'Oriented toward emotional values and responsibilities to loved ones. Caring for family and keeping interactions harmonious comes first.',
        7 => 'Time for looking deep and building knowledge. Keep private space to reflect, learn, and evaluate core issues calmly.',
        8 => 'A day focused on performance and tangible results. Manage work efficiently and make decisive practical choices to establish personal credibility.',
        9 => 'A day to finish, release, and move toward more tolerant values. Close old tasks, reach a settled state, and get ready for the next cycle.',
        11 => 'Sharp intuition acts as the compass for today\'s choices. Pay attention to subtle awareness to make sharp judgments.',
        22 => 'A day for executing systematic plans with a long view. Organizational capacity handles foundational work with flexibility.',
        33 => 'Spread understanding and quiet support to everyone around. Kindness and small practical acts of care are what count.',
    ],
    'hidden_passion' => [
        1 => 'A drive to establish personal identity and take the lead fuels strong inner motivation. Real inspiration comes from making decisions proactively and taking on new challenges.',
        2 => 'A delicate sensitivity and a desire for harmony are always present. Motivation comes from building mutual relationships and contributing to genuine connection.',
        3 => 'The need to express freely and spread positive energy is the core of passion. Tends to look for creative ways to share ideas and inspire others.',
        4 => 'Peace of mind ties to order and values that hold up in the real world. Driven by setting tight structures, working with logical data, and getting everything accurate.',
        5 => 'A craving to experience variety and push personal limits is the main energy source. Changes, new ideas, and the chance to discover something unfamiliar bring real excitement.',
        6 => 'Readiness to carry responsibility and nurture community values acts as a spiritual anchor. Hidden happiness lies in creating a warm, safe environment and genuinely caring for loved ones.',
        7 => 'Intellectual curiosity and a need to get to the bottom of things drive continuous thinking. Satisfaction comes from deep research, examining what is true, and building specialized knowledge.',
        8 => 'Aims for tangible achievement and a clear sense of personal standing. This motivation drives efficiency, effective resource management, and pursuing financial and career goals.',
        9 => 'Compassion and a vision oriented toward meaningful human values act as the compass. A deep need exists to support the community, share genuine understanding, and contribute to collective growth.',
    ],
    'peak' => [
        1 => 'A stage of independence and asserting personal confidence. This cycle is about developing leadership, making autonomous decisions, and taking breakthrough steps.',
        2 => 'A period that highlights harmony and the power of genuine connection. Success comes from listening well, practicing empathy, and staying balanced in social relationships.',
        3 => 'The peak of expressive capacity and creative thinking without a ceiling. The time to show real talent, spread ideas, and build influence through positive communication.',
        4 => 'A cycle that emphasizes practicality, discipline, and persistent effort. Building solid foundations and working methodically are the keys to real, stable results.',
        5 => 'Marked by transformation through personal freedom and flexible adaptation. Seizing opportunities to change and breaking old limits are how experience and vision expand.',
        6 => 'Focused on responsibility to family, community, and human values. The energy of this cycle aims to build harmony, care, and serve the common good.',
        7 => 'A stage that prioritizes inner reflection and accumulating real depth. Learning, researching, and understanding what is actually going on brings sharp awareness of life.',
        8 => 'The peak of prosperity, authority, and practical management capacity. Managing resources efficiently, making decisive moves in business, and establishing standing through outstanding results are the focus.',
        9 => 'A cycle of tolerance and broad humanitarian contribution. Spreading positive values, supporting the community, and completing missions with genuine spiritual meaning.',
        11 => 'A bright time for intuition and sharp spiritual awareness. The power of this stage lies in inspiring, guiding, and leading others with a deep and sensitive vision.',
        22 => 'The capacity to turn large visions into work with lasting systematic value. Building capacity is used to create sustainable, large-scale change.',
        33 => 'The peak of compassion and widespread healing. Unconditional support, bringing peace, and deep understanding for those nearby.',
    ],
    'karmic' => [
        13 => 'Karmic Debt 13/4 centers on lessons of discipline, persistence, and working at the right pace. Avoid shortcuts. Endurance is what actually resolves this.',
        14 => 'Karmic Debt 14/5 centers on lessons of restraint, commitment, and using freedom well. When freedom lacks discipline, energy scatters easily.',
        16 => 'Karmic Debt 16/7 centers on lessons around ego, letting go, and inner restructuring. Collapse often forces a return to genuine values.',
        19 => 'Karmic Debt 19/1 centers on lessons of self-reliance, respecting others, and leading correctly. Autonomy must go hand in hand with responsibility.',
    ],
    'missing' => [
        1 => 'The absence of number 1 points to a need to develop personal confidence, independence, and the ability to initiate.',
        2 => 'The gap at number 2 calls for building sharpness, genuine listening, and empathy toward the surrounding environment.',
        3 => 'Missing number 3 means developing creative thinking and confidently expressing ideas becomes a key area to work on.',
        4 => 'Without number 4, building discipline, attention to detail, and practical foundations for life becomes important.',
        5 => 'The gap at the center of the chart calls for effort in emotional connection, managing freedom, and becoming more flexible with change.',
        6 => 'A lack of number 6 energy needs compensating by learning to balance responsibilities, nurture love, and create harmony at home.',
        7 => 'An empty number 7 signals a need to engage more with direct experience in order to draw lessons and think more deeply.',
        8 => 'The absence of number 8 calls for developing management thinking, decisiveness, and the ability to run things independently.',
        9 => 'Without number 9, defining clear life ideals and developing a genuine sense of responsibility toward the community are key areas to focus on.',
    ],
    'challenge' => [
        0 => '{A quiet cycle without preset pressure from any number, opening free space to find direction and build self-direction.|With no specific energetic barriers, this is a natural resting pace, a chance to map out growth and sharpen independent will.|The empty energy here demands self-leadership, setting goals without being driven by fixed challenges.}',
        1 => '{Sharpen the inner ego and build real confidence, while making sure that confidence does not turn into something that overrides others.|The line between courage and dictatorship is the real challenge. Stand on your own ability while still respecting the world around you.|Work on a quieter ego rather than letting confidence become a shell that imposes on the group.}',
        2 => '{Control the waves of emotional sensitivity, trust intuition, and keep an inner rhythm that does not get thrown off by outside pressure.|Work through the swings. Keep faith solid enough that conflicting opinions cannot knock you off course.|Build emotional limits that protect without isolating. Develop steadiness and let intuition lead.}',
        3 => '{Focus energy on practical goals. Stop letting thoughts and words scatter with every passing inspiration.|Fix the habit of fragmented attention. Filter ideas and put genuine effort into what can actually be made real.|Address the focus problem. Discipline is what turns flying ideas into something tangible.}',
        4 => '{Break through rigid thinking. Build patiently, brick by brick, rather than looking for shortcuts to solid ground.|Brushing against old prejudices forces a loosening of rigidity. Reset discipline and follow the long-term building process.|Clear out stubbornness and make room for persistence. Reorganize life and work with real order.}',
        5 => '{Keep a steady hand against distractions. Balance the drive for freedom with a core compass that does not move.|Work through impulsive urges. Keep a consistent pace and stick to longer-term goals through constant environmental change.|Stay flexibly controlled. Open to new winds but do not slide into instability and quick boredom.}',
        6 => '{Find the balance between compassion and personal freedom. Drop the habit of over-controlling or carrying burdens that belong to others.|Practice love without strings. Learn to put things down and preserve room for independent growth on both sides.|Stay awake when giving care. Draw a clear line between protective love and quiet imposition disguised as responsibility.}',
        7 => '{Break out of extreme cynicism. Loosen the mind enough to touch real experience and draw wisdom from an objective view.|Step down from the tower of personal reasoning. Engage with what is actually happening and turn dry knowledge into something that understands people.|Let go of strict judgment. Accept things as they are and absorb real lessons rather than circling in doubt.}',
        8 => '{Keep hands clean and thinking clear when handling money and power. Refuse to become a servant to ambition or the hunger for achievement.|The test of financial mastery demands fairness, so as not to be consumed by greed or to twist core values.|Build financial independence alongside ethics. Hold steady against temptations that trade dignity for personal gain.}',
    ],
    'pair_matrix' => [
        '1_1' => 'Two 1s together reinforce independence and self-determination. Keep the ego in check or it slides into being dictatorial.',
        '1_2' => 'The drive of 1 gets softened by the sensitivity of 2. Goals get reached through cooperation and genuine understanding of others.',
        '1_3' => 'The confidence of 1 and the creativity of 3 produce real inspiration. There is strong energy for leading and generating ideas.',
        '1_4' => 'Decisiveness from 1 and practicality from 4 help plans get executed methodically and built to last.',
        '1_5' => 'The pairing of 1 and 5 creates fast momentum. Keeping a clear direction prevents getting swept up in constant change.',
        '1_6' => '1 brings initiative while 6 adds responsibility. Personal ambition and care for the collective stay balanced.',
        '1_7' => 'Independent thinking from 1 gets backed by the analytical depth of 7. Every move carries substance and a solid knowledge base.',
        '1_8' => '1 and 8 together zero in on practical results. Management ability and command of material resources get a strong push.',
        '1_9' => '1 and 9 blend strong personality with humanist ideals. The aim is achievement that actually contributes something.',
        '1_11' => '1 alongside 11 creates guidance that runs on intuition. Spiritual core values get grasped quickly and with clarity.',
        '1_22' => 'The vision of 1 and the building capacity of 22 open up the possibility of large-scale projects with real depth of impact.',
        '1_33' => '1 and 33 together turn personal will into a motivation to serve. Community support becomes practical and carries real weight.',
        '2_1' => 'The sensitivity of 2 supports the decisiveness of 1. A flexible and effective working style when leadership is needed.',
        '2_2' => 'Two 2s multiply empathetic energy. Keep emotions steady or decisions become too hesitant at the moments that matter.',
        '2_3' => 'The empathy of 2 harmonizes with the expressiveness of 3. Conveying ideas becomes smooth and touches emotions skillfully.',
        '2_4' => 'The harmony of 2 softens the discipline of 4. Practical plans run more smoothly and hold more steadily.',
        '2_5' => '2 and 5 together create high adaptability. Good relationships hold even during change or instability.',
        '2_6' => '2 and 6 together work toward creating a peaceful space. Care and responsibility get carried out with genuine sincerity.',
        '2_7' => '2 listens while 7 analyzes deeply. The result is thorough thinking that views issues from multiple angles before reaching any conclusion.',
        '2_8' => '2 helps 8 manage resources with flexibility. Practical goals get reached while solid connections with people are maintained.',
        '2_9' => 'The tolerance of 2 resonates with the ideals of 9. Actions get directed toward genuinely humanitarian and selfless community work.',
        '2_11' => 'The sharpness of 2 and 11 together creates real psychological insight. Inner calm is needed to avoid overload from the outside.',
        '2_22' => 'The connecting nature of 2 lays the groundwork for the vision of 22. Building strategic alliances for large projects gets strong support.',
        '2_33' => '2 and 33 together create soothing and uplifting energy, spreading understanding through acts of genuine sharing.',
        '3_1' => 'Creative thinking from 3 and the pioneering nature of 1 help new ideas move quickly and lead the direction.',
        '3_2' => 'Flexible communication from 3 alongside the empathy of 2 creates a tactful approach. Trust comes easily.',
        '3_3' => 'Two 3s strongly amplify expressive capacity. Focus carefully to avoid scattering resources in every direction.',
        '3_4' => 'Inspiration from 3 gets shaped by the practicality of 4. Flying thoughts turn into specific, sustainable results.',
        '3_5' => '3 and 5 together create a lively, innovative pace. Persistence needs practicing to see goals through to the end.',
        '3_6' => 'The creativity of 3 blends with the dedication of 6. Conditions for bonding and nurturing harmony get favorable.',
        '3_7' => 'The depth of 7 sharpens the expression of 3. Personal views spread well and carry real knowledge.',
        '3_8' => 'The sharpness of 3 paired with the confidence of 8 strongly supports negotiating and getting projects done effectively.',
        '3_9' => 'The broad ideals of 9 elevate the communication ability of 3. Creative efforts get directed toward serving the community.',
        '3_11' => 'Intuition from 11 guides the expression of 3. Messages that move people and spark awareness get conveyed.',
        '3_22' => 'The stature of 22 paired with the flexibility of 3 allows deploying large plans by mixing imagination with real execution capacity.',
        '3_33' => 'The healing energy of 33 deepens the soul of 3. Understanding and sharing happen through genuinely inspiring words.',
        '4_1' => 'The consistency of 4 creates solid ground for the pioneering steps of 1. New starts always have careful, practical preparation behind them.',
        '4_2' => '4 brings process to the sensitivity of 2. Tight work structure and a gentle approach fit together well.',
        '4_3' => 'Creative ideas from 3 become real through the organization of 4. Feasibility and sustainability get ensured for every project.',
        '4_4' => 'Two 4s amplify discipline and management capacity. Flexibility needs attention to avoid excessive self-pressure.',
        '4_5' => 'When 4 walks with 5, discipline anchors innovation and personal freedom so they stay on track.',
        '4_6' => '4 and 6 together focus on building family and career foundations through dedication and clear standards.',
        '4_7' => '4 provides a practical frame for the deep research of 7. Knowledge gathered becomes highly applicable to real life.',
        '4_8' => 'Execution capacity from 4 resonating with the management thinking of 8 creates visible, stable material results over time.',
        '4_9' => 'Practicality from 4 strongly supports the ideals of 9. The desire to contribute gets turned into concrete, practical action.',
        '4_11' => 'The stability of 4 helps intuitive messages from 11 land more clearly and stay closer to everyday reality.',
        '4_22' => 'The building energy of 22 gets reinforced by the foundation of 4. Complex, large-scale projects can be deployed.',
        '4_33' => 'The thoroughness of 4 walks with the compassion of 33. A safe, genuinely committed support environment for the community gets created.',
        '5_1' => 'The flexibility of 5 resonating with the pioneering nature of 1 drives fast breakthroughs. Consistency prevents goals from changing too soon.',
        '5_2' => 'When 5 pairs with 2, adaptation gets softened by sensitivity. Harmony holds even in highly volatile environments.',
        '5_3' => 'Lively energy from 5 and 3 together creates strong creativity. Activities get refreshed, but focus is needed for the best results.',
        '5_4' => '5 brings innovation to the solid base of 4. Practical plans gain mobility without losing their underlying discipline.',
        '5_5' => 'Two 5s amplify the craving for freedom and experience. High self-control is needed to avoid distraction and impatience.',
        '5_6' => '5 and 6 together often pull in two directions: craving freedom on one side, affection and responsibility on the other. The challenge is holding both without feeling stuck.',
        '5_7' => 'Adaptability from 5 paired with analytical thinking from 7 produces deep lessons through real discovery and experience.',
        '5_8' => 'The confidence of 8 directs the dynamic nature of 5 into practical goals. Sharp situational handling produces concrete results.',
        '5_9' => '5 and 9 together expand personal vision toward human values. Reform actions for the community\'s benefit get promoted.',
        '5_11' => 'The changing energy of 5 gets guided by the intuition of 11. New trends and spiritual values get grasped quickly.',
        '5_22' => 'The stature of 22 finds support from the flexibility of 5. Large-scale projects can be deployed using approaches that actually work now.',
        '5_33' => 'The compassion of 33 soothes the restlessness of 5. Personal freedom gets directed toward spreading love and understanding.',
        '6_1' => 'Responsibility from 6 and decisiveness from 1 form a dedicated leadership style that protects and serves common interests.',
        '6_2' => 'When 6 walks with 2, the ability to nurture harmony reaches its peak. A gentle, well-connected living and working space gets created.',
        '6_3' => 'Creative energy from 3 enriches the dedication of 6. Caring for and supporting others becomes flexible and genuinely inspiring.',
        '6_4' => 'Discipline from 4 creates solid structure for the love of 6. Responsibilities get turned into practical, persistent action.',
        '6_5' => '6 and 5 together usually want to care for others while needing personal space. Holding both without feeling trapped is the real challenge.',
        '6_6' => 'Two 6s emphasize deep compassion. Watch for taking on too much or getting too involved in others\' lives.',
        '6_7' => '6 and 7 together bring a thorough perspective on responsibility. Genuinely valuable lessons get drawn from dedicated service.',
        '6_8' => 'The confidence of 8 directs the care of 6 into practical goals. Concrete outcomes get created to ensure the welfare of the group.',
        '6_9' => 'The wide vision of 9 expands the compassion of 6. Dedication moves from family into broader humanitarian ideals.',
        '6_11' => 'Intuition from 11 guides the empathy of 6. The quiet spiritual needs of those nearby get recognized and supported promptly.',
        '6_22' => 'The capacity of 22 combined with 6 allows sustainable community projects to be deployed. Care gets organized at a larger scale.',
        '6_33' => '6 and 33 together create strong healing energy. Balance is needed to support others without depleting yourself.',
        '7_1' => 'When analytical thinking from 7 walks with the decisiveness of 1, pioneering choices always rest on a knowledge base and careful observation.',
        '7_2' => 'The empathy of 2 softens the closed exterior of 7. Deep listening and understanding of subtle environmental signals become possible.',
        '7_3' => 'The expressive ability of 3 makes the knowledge that 7 draws together more approachable, more alive, and easier to spread.',
        '7_4' => '7 and 4 together create tight logical thinking. Authenticity and verification in all practical action get prioritized.',
        '7_5' => 'Real-world experience from 5 provides rich material for the contemplation of 7. Lessons emerge through discovery and genuine novelty.',
        '7_6' => 'Responsibility from 6 directs the thinking of 7 toward understanding and caring for people. Harmony in close relationships follows.',
        '7_7' => 'Two 7s push deep research capacity. Openness needs active attention to avoid falling into isolation or excessive cynicism.',
        '7_8' => 'The decisiveness of 8 combined with the depth of 7 creates sharp strategic vision. Success gets built on solid preparation.',
        '7_9' => 'The humanist ideals of 9 elevate the contemplation of 7. Thinking gets directed toward life meaning and a spirit of community service.',
        '7_11' => 'Sharp intuition from 11 supports the analytical ability of 7. Outstanding awareness of spiritual values and how life works gets formed.',
        '7_22' => 'The building stature of 22 finds its footing in the thoroughness of 7. Large projects can be deployed with detailed plans and solid roadmaps.',
        '7_33' => 'The understanding of 7 blends with the compassion of 33. Spiritual support gets built on deep empathy and genuine healing energy.',
        '8_1' => 'Decisiveness from 1 alongside the management confidence of 8 creates strong execution power. Projects get led to real results.',
        '8_2' => 'The flexibility from 2 helps 8 run things more smoothly. Sustainable relationships get maintained while hitting the performance that was set.',
        '8_3' => 'Expressive ability from 3 adds persuasive power to the management thinking of 8. Dry plans turn into inspiration for the team.',
        '8_4' => 'When 8 combines with 4, persistence and discipline run high. Valuable achievements get built to hold steady over time.',
        '8_5' => 'Flexibility from 5 helps 8 adapt quickly to shifts. New ways to optimize work results get found.',
        '8_6' => 'Responsibility from 6 directs the energy of 8 toward protecting and caring for common interests. Success and harmony stay balanced.',
        '8_7' => 'Contemplation from 7 adds strategic depth to 8. Management decisions always carry thoroughness and a long-term view.',
        '8_8' => 'Two 8s amplify executive capacity and authority. Balance needs attention to avoid excessive pressure around achievement.',
        '8_9' => 'Humanist ideals from 9 direct the strength of 8 toward genuinely significant goals. Sustainable benefit gets delivered to the community.',
        '8_11' => 'Intuition from 11 guides the confidence of 8. Subtle opportunities get identified and a career gets built on real values.',
        '8_22' => 'The execution capacity of 22 coordinates with 8 to deploy highly systematic projects at a significant scale.',
        '8_33' => 'The compassion of 33 softens the rigidity of 8. Management becomes more human and earns genuine consensus.',
        '9_1' => 'People with 9 and 1 together tend to lead by looking past personal gain, but stay decisive enough to act when needed. They do not wait for everyone to agree before moving.',
        '9_2' => 'The tolerant heart of 9 combined with the sensitivity of 2 creates a real ability to bring people together through deep empathy.',
        '9_3' => 'Flexible communication from 3 helps spread the humanist ideals of 9 in ways that land. Positive impact comes easily.',
        '9_4' => '4 brings discipline and practicality to the ambitions of 9. Community service goals get materialized sustainably.',
        '9_5' => 'Flexibility from 5 expands the scope of activity for 9. Quick adaptation to innovative approaches for the common good becomes possible.',
        '9_6' => 'Kindness from 6 and the responsible spirit of 9 create warm, caring energy aimed at peace in both family and society.',
        '9_7' => 'Thorough thinking from 7 helps 9 see the core of issues clearly. Life directions with real intellectual value get offered.',
        '9_8' => 'Management capacity from 8 directs the strength of 9 toward specific outcomes. Material success and personal ideals stay balanced.',
        '9_9' => 'Two 9s strongly push selflessness and a wide perspective. Staying alert to what is actually feasible in action is necessary.',
        '9_11' => 'Sharp intuition from 11 guides the kind heart of 9. A particular spiritual connection and real understanding of human depth get created.',
        '9_22' => 'The desire to contribute from 9 finds a strong execution tool in 22. Opportunities open up to build lasting works for the community.',
        '9_33' => 'The healing power of 33 deepens the ideals of 9. Effort gets directed toward lifting and easing the pain of those nearby.',
        '11_1' => 'The independent confidence of 1 gets guided by the intuition of 11/2. An inspiring and perceptive pioneering style emerges.',
        '11_2' => 'Sensitivity from 2 resonating with 11/2 creates excellent psychological insight. Stillness is needed to avoid emotional overload.',
        '11_3' => 'Creative thinking from 3 brings spiritual messages from 11/2 to life. Ideas get conveyed with depth and real pull.',
        '11_4' => 'Discipline from 4 provides a practical frame for inspiration from 11/2. Abstract ideas get materialized in an organized way.',
        '11_5' => 'The need for novelty from 5 combined with the intuition of 11/2 drives flexible adaptation based on reading the right moment accurately.',
        '11_6' => 'Kindness from 6 and the empathy of 11/2 are aimed at spiritual care for the community. Sincerity is what builds harmony.',
        '11_7' => 'Contemplation from 7 deepens the awareness of 11/2. A worldview that carries both knowledge and real lived experience gets formed.',
        '11_8' => 'The management power of 8 directs inspiration from 11/2 into practical goals. Achievement gets built on sharp, intuitive vision.',
        '11_9' => 'Ideals from 9 expand the scale for the intuition of 11/2. Personal energy gets aimed at human values and broader social service.',
        '11_11' => 'Two 11/2s strongly amplify mental capacity. High inner mastery is needed to stay balanced against the pressure of that sensitivity.',
        '11_22' => 'Intuition from 11/2 coordinating with the building capacity of 22/4 allows deploying large projects with genuine spiritual and practical depth.',
        '11_33' => 'Soothing energy from 33/6 deepens the empathy of 11/2. Love gets spread through a genuine understanding of people.',
        '22_1' => 'The determination of 1 acts as a springboard for the ambitious projects of 22/4. Initiative and pioneering confidence bring the vision into reality.',
        '22_2' => 'The connection between 22/4 and 2 builds a solid collaborative network. Large-scale work gets brought to reality through smooth coordination.',
        '22_3' => 'Creative power from 3 adds flexibility to 22/4. Massive structures become more alive and applicable in real life.',
        '22_4' => 'The foundation of 4 deepens the solidity of 22/4. Every small detail contributes to the durability of large plans.',
        '22_5' => 'Flexibility from 5 opens up modern operating approaches. The large projects of 22/4 adapt well to changing circumstances.',
        '22_6' => '6 orients the goals of 22/4 toward serving people. Love and responsibility create something that lasts.',
        '22_7' => 'The depth of 7 brings sharp strategic thinking to 22/4. Every building action carries intellectual meaning and long-range vision.',
        '22_8' => 'The management confidence from 8 resonates with the execution capacity of 22/4. Tangible results and stable resources come into focus.',
        '22_9' => 'The desire to contribute from 9 expands the building scale of 22/4. Building strength gets aimed at lasting community works.',
        '22_11' => 'Sharpness from 11/2 guides the building capacity of 22/4. Spiritual ideas get specified into practical value.',
        '22_22' => 'Building energy hits maximum when 22/4 repeats. The power to realize ambitious goals comes with strict discipline requirements.',
        '22_33' => 'Understanding from 33/6 softens the practicality of 22/4. Large-scale building capacity and the mission of lifting people blend well.',
        '33_1' => 'Initiative from 1 rests on the compassionate foundation of 33/6. Leading actions always aim to support and protect shared interests.',
        '33_2' => 'Empathy from 2 blends with the compassion of 33/6. A delicate, sincere approach creates real ability to soothe and connect.',
        '33_3' => 'Creative energy from 3 helps spread the ideals of 33/6 vividly. Empathy turns into words and actions with genuine persuasive power.',
        '33_4' => '4 provides a practical frame for 33/6 to deploy support activities. Love gets turned into something that lasts.',
        '33_5' => 'Flexibility from 5 brings fresh methods to the mission of 33/6. Sharing adapts well to how life keeps changing.',
        '33_6' => 'Interaction between 33/6 and 6 highlights nurturing responsibility. Knowing how to stay balanced to avoid depleting energy is important.',
        '33_7' => 'The depth of 7 helps 33/6 see what others actually need. Real healing comes from intellect and genuine contemplation.',
        '33_8' => 'Management confidence from 8 directs the kindness of 33/6 practically. Real resources get created to ensure stability for those nearby.',
        '33_9' => '33/6 and 9 together expand service to a community scale. Selfless vision points all effort toward genuinely humanist goals.',
        '33_11' => 'Intuition from 11/2 mixed with compassion from 33/6 creates a particular empathy. Souls get soothed with outstanding sensitivity.',
        '33_22' => 'The building stature of 22/4 brings the mission of 33/6 to life at scale. Genuinely human living environments get built.',
        '33_33' => 'Support energy reaches high intensity when 33/6 repeats. Self-care skills are needed to stay resilient on the path of service.',
    ],
    'arrows' => [
        'Intellect' => [
            'nums' => '3 6 9',
            'present' => 'Sharp logical thinking, solid retention, and consistent processing of information. Facing a new problem, the mind immediately sorts priorities, connects the facts, and assembles clear pieces. This mental energy creates real momentum for research, strategy, and getting to the actual substance of things.',
            'missing' => 'Absorbs new knowledge more slowly, especially information that requires sustained focus and linking. Thought gets scrambled when too many signals arrive at once, slowing down the formation of any overall picture. A steady learning pace only develops when strict structural principles are already in place.'
        ],
        'Emotion' => [
            'nums' => '2 5 8',
            'present' => 'A rich inner world. Moves delicately with personal emotions and what is happening around them. Sharp intuition picks up the atmosphere and small shifts in relationships, opening the way for genuine, deep connections.',
            'missing' => 'The personal emotional flow sometimes clogs. Usually takes a long time to truly open up. Gets stuck reading others\' emotions due to a habit of keeping distance or not expressing what is inside. This throws off the rhythm of connection.'
        ],
        'Action' => [
            'nums' => '1 4 7',
            'present' => 'Powerful execution energy. Always grounds itself in discipline and persistence to reach the finish line. Does not let ideas float. The strength here converts thought into specific action aimed straight at visible results. Endurance and responsibility stay high in every task.',
            'missing' => 'Action discipline breaks easily through procrastination or getting swept into passing inspiration. Holds many intentions but struggles to maintain a steady enough pace to produce visible results. Often runs into difficulty keeping motivation alive until the end without fixed habits in place.'
        ],
        'Planning' => [
            'nums' => '1 2 3',
            'present' => 'Sharp at organizing how work connects. Knows how to break goals down and arrange priorities tightly. A wide perspective spots the links between tasks, which balances time and resources well. Once a roadmap is set, execution energy gets optimized and holds up against distraction.',
            'missing' => 'Gets stuck facing sequential processes or tasks that need detailed roadmaps. A disconnected organizational view causes work to fall apart and makes progress hard to track. Over long journeys, a significant amount of time gets consumed just trying to find direction.'
        ],
        'Willpower' => [
            'nums' => '4 5 6',
            'present' => 'Solid mental resilience. Absorbs pressure well and stays on track in harsh conditions. Once locked onto a goal, the drive to hold on runs at full capacity. Does not easily step back when blocked. This inner strength is what keeps things steady through rough periods.',
            'missing' => 'The mindset wobbles when hitting big barriers or a rush of pressure. The drive to hold on wears down. Thoughts of retreating or veering off early come easily when results do not show up as expected. A fragile inner fire makes reaching distant goals genuinely difficult.'
        ],
        'Result' => [
            'nums' => '7 8 9',
            'present' => 'Vision projects far ahead. Zooms out for a wide view and targets the finish line rather than circling minor details. This creates momentum to sketch the future and chase big ideals. This converging energy builds solid ground for a clear life trajectory.',
            'missing' => 'Focus tends to get stuck in the present or in close-up situations. The big picture easily gets distorted or blurry. Without a far-sighted compass, core goals dilute and the real destination becomes harder to pinpoint. Long-term moves lose their ability to build meaningful results.'
        ],
        'Determination' => [
            'nums' => '3 5 7',
            'present' => 'Deeply rooted stance. Firmly holds decisions and stays unshaken by outside pressure once the inner desire is clear. Steady energy builds a consistent trajectory and reaches full power when high concentration is needed. This carries a piercing quality, moving straight toward the goal.',
            'missing' => 'Decision roots shake before opposing views or shifting circumstances. Lacking firmness causes the position to keep bending to the environment. This wears down commitment and pushes the process of reaching goals into an uncertain state.'
        ],
        'Sensitivity' => [
            'nums' => '1 5 9',
            'present' => 'An extremely sharp intuitive antenna. Catches the essence of situations even before the shape has fully formed. Unlocking emotional states and reading small vibrations in a space produces delicate reflexes. This sharpness is the key to genuinely understanding people and navigating the rhythm of communication.',
            'missing' => 'The connection to the inner voice tends to lag. Makes it difficult to catch fragile emotional signals or subtle shifts in context. Tends to rely on visible cues to set feelings rather than receiving them directly. This delay reduces sharpness when navigating emotionally charged situations.'
        ]
    ],
    'repeating_numbers' => [
        1 => [
            2 => 'Words and actions hold together with real consistency. This reflects practical thinking and a clear inner world. That honesty builds solid trust across all connections.',
            3 => 'The inner state keeps swinging between two poles: open and enthusiastic one moment, then quiet and closed the next. This unpredictable rhythm creates an invisible gap that makes real emotions hard to read.',
            4 => 'Runs into difficulty understanding itself and naming what it actually feels. When feelings cannot be clearly identified, showing a genuine inner world to others becomes a significant challenge.'
        ],
        2 => [
            2 => 'Sharp intuition at an ideal balance. Things get grasped quickly and situations get read accurately. Sensitive perception produces appropriate responses to even the smallest shifts.',
            3 => 'Emotional energy crosses a stable threshold. Easily knocked around by outside influence. When sensitivity speaks too loudly, a lot of quiet space is needed to pull the mind back to balance.',
            4 => 'A fragile inner world that reacts strongly to even small bumps. Genuinely needs solid mental anchors to heal and push through pressure.'
        ],
        3 => [
            2 => 'Flexible thinking and a rich imagination create big strengths in words and creativity. This energy fits well in media, art, or visual expression.',
            3 => 'The tendency to drift high gets stronger. Sometimes pulls the mind away from practical demands. Ideas flow abundantly but lack the grounding to actually take shape in life.',
            4 => 'Imagination power widens the gap between the world of thought and the real ground. Without restraint, flying concepts reduce the practical application of what is actually being worked on.'
        ],
        4 => [
            2 => 'Discipline and a practical lens bring real organizational skill to work. This energy performs best in environments with clear rules and standards.',
            3 => 'Tends to lock itself into rigid patterns or place heavy weight on personal and material limits. This kind of rigidity cuts flexibility and shrinks how much can be seen.',
            4 => 'Entrenched patterns sit deep. Causes defensiveness or sharp reactions to changes that break habits. Stubbornness limits adaptation and loses necessary softness.'
        ],
        5 => [
            2 => 'A craving for experience and freedom comes with an independent, fiery personality. This lively energy flow makes adapting across many different situations feel natural.',
            3 => 'Emotional swings create hidden internal tension. This unstable state breaks consistency and makes it hard to sustain decisions.',
            4 => 'Strong inner conflicts easily lead to overreaction or losing control at sensitive moments. This explosive energy drains fast if left unchecked.'
        ],
        6 => [
            2 => 'Family responsibility always runs alongside a strong creative flow. This harmonious rhythm builds tight bonds while enriching life with a personal mark.',
            3 => 'A constant state of underlying worry, especially when the mind gets weighted down by emotional knots or responsibility burdens. Stored tension wears down core peace.',
            4 => 'The creative spring gets covered by negative emotions and the block of self-imposed expectation pressure. In this state, defensiveness takes over from openness to new things.'
        ],
        7 => [
            2 => 'Growth gets engraved deeply through lessons drawn from direct experience. Every event builds cognitive depth and shapes a solid set of life values.',
            3 => 'The awakening process often starts from major turning points that force a re-evaluation of what life is actually about. These curves mark strong phases of shedding in how things are understood.',
            4 => 'Gets forced to rebuild the entire value system after passing through harsh barriers. Shedding is difficult but forges real inner strength and genuine maturity.'
        ],
        8 => [
            2 => 'Sharp practical thinking mixed with an independent work style creates a strong action pace. Using this edge well makes hitting big targets very precise.',
            3 => 'Easily falls into feeling lost when the destination blurs or circumstances shift too quickly. This instability wears down confidence and makes decisions hesitant.',
            4 => 'Carries a large reservoir of execution energy. But it easily bursts into impulsiveness without regulation. Without control, this strength becomes pressure instead of achievement.'
        ],
        9 => [
            2 => 'A heart aimed at contribution and genuine human values for the community. This motivation shapes a meaningful life and refuses anything shallow or hollow.',
            3 => 'The idealized view reaches too far. It creates a beautiful lens but has no practical anchor. This imbalance easily brings disappointment when life does not match the spiritual expectation.',
            4 => 'Tends to sink into a private ideal world, naturally widening the distance from ordinary standards. Moving away from reality makes everyday friction heavier and harder to adapt to.'
        ]
    ]
];